id: P4056D9B6
initial_creation_type: input
source_metadata:
  title: Prajñāpāramitā
  parent: 1. Commentaries on the Eighteen Great Treatises
  source: https://sakyalibrary.com
  bases:
    401d:
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་བྱ་བ་བཞུགས་སོ།།
      author: བྱམས་པ་མགོན་པོ།
      base_file: 401d.txt
      order: 1
    d004:
      title: ཤེར་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་ཞེས་བྱ་བའི་འགྲེལ་པ་དོན་གསལ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: སློབ་དཔོན་སེང་གེ་བཟང་པོ།
      base_file: d004.txt
      order: 2
    08fd:
      title: མངོན་རྟོགས་རྒྱན་དང་འགྲེལ་པ་དོན་གསལ་རྩ་འགྲེལ་གྱི་དགོས་དོན་སྩོལ་བ་རིན་ཆེན་བསམ་འཕེལ་རྒྱལ་པོ།
      author: གཡག་སྟོན་སངས་རྒྱས་དཔལ།
      base_file: 08fd.txt
      order: 3
    8bc1:
      title: གཡག་པའི་འཕགས་གསུམ་རྟོགས་རིགས་བཞུགས་སོ།།
      author: གཡག་སྟོན་སངས་རྒྱས་དཔལ།
      base_file: 8bc1.txt
      order: 4
    e9ae:
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་འགྲེལ་པའི་རྣམ་བཤད་ཚིག་དོན་རབ་ཏུ་གསལ་བ།
      author: རོང་སྟོན་ཤཱཀྱ་རྒྱལ་མཚན།
      base_file: e9ae.txt
      order: 5
    b808:
      title: མངོན་པར་རྟོགས་པའི་རྒྱན་འགྲེལ་པ་དང་དཀའ་བའི་གནས་རྣམ་པར་འབྱེད་པ་ཟབ་དོན་གནད་ཀྱི་ཟླ་འོད་ཅེས་བྱ་བ།
      author: རོང་སྟོན་ཤཱཀྱ་རྒྱལ་མཚན།
      base_file: b808.txt
      order: 6
    13d5:
      title: མངོན་པར་རྟོགས་པའི་རྒྱན་འགྲེལ་པ་དང་བཅས་པའི་རྒྱས་འགྲེལ་བཤད་སྦྱར་ཡིད་ཀྱི་མུན་སེལ་བྱ་བ།།
        པོད་གཉིས་ལས་སྟོད་ཆ།
      author: ཉ་དབོན་ཀུན་དགའ་དཔལ།
      base_file: 13d5.txt
      order: 7
    16de:
      title: མངོན་པར་རྟོགས་པའི་རྒྱན་འགྲེལ་པ་དང་བཅས་པའི་རྒྱས་འགྲེལ་བཤད་སྦྱར་ཡིད་ཀྱི་མུན་སེལ་བྱ་བ།།
        པོད་སྨདཆ།
      author: ཉ་དབོན་ཀུན་དགའ་དཔལ།
      base_file: 16de.txt
      order: 8
    cbdd:
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་འགྲེལ་པ་དང་བཅས་པའི་དཀའ་བའི་གནས་རྣམ་པར་བཤད་པ་ཡུམ་དོན་རབ་གསལ་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: cbdd.txt
      order: 9
    f687:
      title: ཞུགས་གནས་ཀྱི་རྣམ་གཞག་སྐྱེས་བུ་མཆོག་གི་གསལ་བྱེད་ཅེས་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: f687.txt
      order: 10
    ab83:
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་རྟོགས་རྒྱན་གྱི་གཞུང་སྔ་ཕྱིའི་འབྲེལ་དང་དཀའ་གནས་ལ་དཔྱད་པ་སྦས་དོན་ཟབ་མོའི་གཏེར་གྱི་ཁ་འབྱེད་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: ab83.txt
      order: 11
    cde1:
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་འགྲེལ་པ་དང་བཅས་པའི་ངག་དོན་སྦས་དོན་ཟབ་མོའི་གནད་ཀྱི་སྒྲོན་མེ་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: cde1.txt
      order: 12
    a755:
      title: མཐར་གྱིས་གནས་པའི་སྙོམས་པར་འཇུག་པའི་རྣམ་བཤད་སྙོམས་འཇུག་རབ་གསལ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: a755.txt
      order: 13
    3bab:
      title: རྟེན་འབྲེལ་གྱི་རྣམ་པར་བཞག་པ་འཁོར་འདས་རབ་གསལ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: 3bab.txt
      order: 14
    60f1:
      title: ལེགས་པར་བཤད་པ་ལུང་རིགས་ཀྱི་རྒྱ་མཚོ་བྱ་བ་བཞུགས་སོ།། པོད་གཉིས་ལས་སྟོད་ཆ།
      author: འབྲས་ཡུལ་ཀུན་དགའ་ཆོས་བཟང་།
      base_file: 60f1.txt
      order: 15
    34e8:
      title: ལེགས་པར་བཤད་པ་ལུང་རིགས་ཀྱི་རྒྱ་མཚོ་བྱ་བ་བཞུགས་སོ།། པོད་སྨད་ཆ།
      author: འབྲས་ཡུལ་ཀུན་དགའ་ཆོས་བཟང་།
      base_file: 34e8.txt
      order: 16
    d3d8:
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་དཀའ་འགྲེལ་སྦས་དོན་ཟབ་མོའི་གཏེར་གྱི་ཁ་འབྱེད་ཀྱི་དགོངས་འགྲེལ་བྱ་བ་བཞུགས་སོ།།
      author: མཁན་ཆེན་ངག་ཆོས།
      base_file: d3d8.txt
      order: 17
    1fd3:
      title: ཐེག་པ་ཆེན་པོ་མདོ་སྡེའི་རྒྱན་ཞེས་བྱ་བའི་ཚིག་ལེའུར་བྱས་པ་བཞུགས་སོ།།
      author: བྱམས་པ་མགོན་པོ།
      base_file: 1fd3.txt
      order: 18
    edad:
      title: མདོ་སྡེ་རྒྱན་གྱི་རྣམ་བཤད་ཐེག་ཆེན་གསལ་བར་བྱེད་པའི་གནད་ཀྱི་སྒྲོན་མེ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: རོང་སྟོན་ཤཱཀྱ་རྒྱལ་མཚན།
      base_file: edad.txt
      order: 19
    4c2b:
      title: ཐེག་པ་ཆེན་པོ་མདོ་སྡེའི་རྒྱན་གྱི་འགྲེལ་པ་རིན་པོ་ཆེའི་ཕྲེང་བ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: འཕགས་པ་ཐོགས་མེད།
      base_file: 4c2b.txt
      order: 20
    936d:
      title: དབུས་དང་མཐའ་རྣམ་པར་འབྱེད་པའི་ཚིག་ལེའུར་བྱས་པ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: མགོན་པོ་བྱམས་པ།
      base_file: 936d.txt
      order: 21
    58f6:
      title: དབུས་དང་མཐའ་རྣམ་པར་འབྱེད་པའི་རྣམ་པར་བཤད་པ་མི་ཕམ་དགོངས་རྒྱན་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: རོང་སྟོན་ཤཱཀྱ་རྒྱལ་མཚན།
      base_file: 58f6.txt
      order: 22
    f474:
      title: དབུས་མཐའ་རྣམ་འབྱེད་ཀྱི་འགྲེལ་པ་དབུ་མའི་རྒྱན་བཞུགས་སོ།།
      author: གནས་དྲུག་པ།
      base_file: f474.txt
      order: 23
    f3bc:
      title: ཆོས་དང་ཆོས་ཉིད་རྣམ་པར་འབྱེད་པ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: མགོན་པོ་བྱམས་པ།
      base_file: f3bc.txt
      order: 24
    10c4:
      title: ཆོས་དང་ཆོས་ཉིད་རྣམ་པར་འབྱེད་པའི་ཚིག་ལེའུར་བྱས་པ་བཞུགས་སོ།།
      author: མགོན་པོ་བྱམས་པ།
      base_file: 10c4.txt
      order: 25
    9c94:
      title: ཆོས་དང་ཆོས་ཉིད་རྣམ་པར་འབྱེད་པའི་རྣམ་བཤད་ལེགས་པར་འདོམས་པ་ལྷའི་རྔ་བོ་ཆེ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: རོང་སྟོན་ཤཱཀྱ་རྒྱལ་མཚན།
      base_file: 9c94.txt
      order: 26
    66da:
      title: ཆོས་ཉིད་རྣམ་འབྱེད་ཀྱི་འགྲེལ་པ་བཞུགས་སོ།།
      author: སྟག་ཚང་ལོ་ཙཱ་བ།
      base_file: 66da.txt
      order: 27
    1cf3:
      title: ཐེག་པ་ཆེན་པོ་རྒྱུད་བླ་མའི་བསྟན་བཅོས་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: མགོན་པོ་བྱམས་པ།
      base_file: 1cf3.txt
      order: 28
    90ce:
      title: ཐེག་པ་ཆེན་པོ་རྒྱུད་བླ་མའི་བསྟན་བཅོས་ཀྱི་རྣམ་པར་བཤད་པ་ངེས་དོན་རབ་གསལ་སྣང་བ་བཞུགས་སོ།།
      author: ས་བཟང་འཇམ་དབྱངས་བློ་གྲོས།
      base_file: 90ce.txt
      order: 29
    940c:
      title: ཐེག་པ་ཆེན་པོ་རྒྱུད་བླ་མའི་བསྟན་བཅོས་ལེགས་པར་བཤད་པ་བཞུགས་སོ།།
      author: རོང་སྟོན་ཤཱཀྱ་རྒྱལ་མཚན།
      base_file: 940c.txt
      order: 30
    cd5e:
      title: ཐེག་པ་ཆེན་པོ་རྒྱུད་བླ་མའི་བསྟན་བཅོས་ལེགས་བཤད་ཉི་མའི་འོད་ཟེར་དབུས་ཕྱོགས་བྱ་བ་བཞུགས་སོ།།
      author: དོལ་པོ་པ་ཤེས་རབ་རྒྱལ་མཚན།
      base_file: cd5e.txt
      order: 31
    d69a:
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: རྒྱལ་སྲས་ཞི་བ་ལྷ།
      base_file: d69a.txt
      order: 32
    b271:
      title: བྱང་ཆུབ་སེམས་པའི་སྤྱོད་པ་ལ་འཇུག་པའི་ཟིན་བྲིས་འཇམ་དཔལ་ཞལ་ལུང་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ལྷོ་པ་ཀུན་མཁྱེན་རིན་ཆེན་གྱི་ས་པཎ་གསུང་ལ་ཟིན་བྲིས།
      base_file: b271.txt
      order: 33
    0ed4:
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་རྣམ་པར་བཤད་པ་གཞུང་དོན་རབ་གསལ་སྣང་བ་བཞུགས་སོ།།
      author: ས་བཟང་འཇམ་དབྱངས་བློ་གྲོས།
      base_file: 0ed4.txt
      order: 34
    401b:
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་འགྲེལ་པ་ལེགས་པར་བཤད་པའི་རྒྱ་མཚོ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: དངུལ་ཆུ་ཐོགས་མེད།
      base_file: 401b.txt
      order: 35
    a17a:
      title: སྤྱོད་འཇུག་ཤེར་ལེའི་རྒྱ་ཆེར་འགྲེལ་མཆན་སྙིང་པོའི་དོན་གསལ་ཉིན་བྱེད་ཆེན་པོ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: བླ་མ་བློ་གྲོས་རྒྱལ་མཚན།
      base_file: a17a.txt
      order: 36
    ce4a:
      title: རྒྱལ་ཡུམ་སྙིང་པོའི་རྣམ་བཤད་ཉིན་བྱེད་དབང་པོ།
      author: འཇམ་དབྱངས་ཀུན་དགའ་ཆོས་བཟང་གི་སློབ་མ་གཞུང་བརྒྱ་པ་དངོས་གྲུབ་དཔལ་འབར།
      base_file: ce4a.txt
      order: 37
    715f:
      title: ས་ལམ་གྱི་རྣམ་པར་གཞག་པ་དགོངས་པ་གསལ་བའི་ཉི་འོད།
      author: ཀུན་མཁྱེན་གྱི་སློབ་མ་རྭ་བན་ཡོན་ཏན་འབྱུང་གནས།
      base_file: 715f.txt
      order: 38
    d1cb:
      title: རྒྱུད་བླ་མའི་བསྟན་བཅོས་ཀྱི་ངེས་དོན་གསལ་བར་བྱེད་པ་རིན་པོ་ཆེའི་སྒྲོན་མེ།
      author: གནས་ཕྲུག་པ།
      base_file: d1cb.txt
      order: 39
    51f4:
      title: སུམ་ཅུ་པ་དང་ཉི་ཤུ་པའི་རབ་ཏུ་བྱེད་པ།
      author: པཎ་ཆེན་ཤཱཀྱ་མཆོག་ལྡན།
      base_file: 51f4.txt
      order: 40
    fb84:
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་དཀའ་འགྲེལ་དང་ལུང་སྦྱོར་མདོར་བསྡུས་འཇམ་དབྱངས་བླ་མའི་དགོངས་གསལ།
      author: ཀུན་དགའ་རྣམ་རྒྱལ།
      base_file: fb84.txt
      order: 41
    a059:
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ་ལས་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་ལེའུའི་འགྲེལ་བ་གཞུང་དོན་འཁྲུལ་མེད་གསལ་བའི་ཉི་འོད།
      author: ཀུན་དགའ་རྣམ་རྒྱལ།
      base_file: a059.txt
      order: 42
    b814:
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་བསྡུས་དོན་འཇམ་དབྱངས་བླ་མའི་ཞལ་ལུང་།
      author: ཀུན་དགའ་རྣམ་རྒྱལ།
      base_file: b814.txt
      order: 43
    6c89:
      title: བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་བརྗོད་བྱའི་གཙོ་བོ་དོན་བདུན་ཅུའི་རྣམ་བཤད་ངོ་མཚར་འོད་ཟེར་གྱི་འཕྲེང་བ།
      author: གྲགས་པ་ཐོགས་མེད།
      base_file: 6c89.txt
      order: 44
created_at: '2022-04-06T15:45:01.479197'
last_modified_at: '2022-04-06T15:45:01.479250'
